config/routes.rb
Rails.application.routes.draw do
  root :to => 'images#new'
  resources :images do
    collection do
      post :upload
      get :list
      get :about
      post :trans
    end
  end

end

app/models/gcv.rb
class Gcv
  attr_accessor :endpoint_uri, :file_path

  def initialize(file_path)
    @endpoint_uri = "https://vision.googleapis.com/v1/images:annotate?key=#{ENV['SERVER_KEY']}"
    @file_path = file_path
  end

  def request
    http_client = HTTPClient.new
    content = Base64.strict_encode64(File.new(file_path).read)
    response = http_client.post_content(endpoint_uri, request_json(content), 'Content-Type' => 'application/json')
    return JSON.parse(response)['responses'].first['textAnnotations'].first['description'].split(' ')
    #result_parse(response)
  end

  private

  def request_json(content)
    {
      requests: [{
        image: {
          content: content
        },
        features: [{
          type: "TEXT_DETECTION",
          maxResults: 10
        }]
      }]
    }.to_json
  end

  #def result_parse(response)
    #result = JSON.parse(response)['responses'].first

      #text = result['textAnnotations'].first
      #result = "これは、#{text['locale']}です。\n-----\n#{text['description']}"
#JSON.parse(response)['responses'].first['textAnnotations'].first['description'].split(' ')
    #return JSON.parse(response)['responses'].first['textAnnotations'].first['description'].split(' ')
  #end
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, FileUploader
  validates :file, presence: true
end

app/controllers/application_controller.rb
# hoeeeeee
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_env
    case Rails.env
      when 'production'
        return "pro"
      when 'development'
        return "dev"
      when 'test'
        return "test"
    end
  end
end

app/controllers/images_controller.rb
# add
class ImagesController < ApplicationController
  permits :file
  require 'time'
  require "tinify"

  def new
    @image = Image.new
  end

  def upload
    if(params[:image])
      @image = Image.new(file: params[:image][:file])
    else
      @image = Image.new
    end
    if @image.save
      env_prefix = get_env
      resized_path = "#{env_prefix}/uploads/image/file/#{@image.id}/300/#{params[:image][:file].original_filename}"
      @image.path = resized_path
      @image.save
      save_light_img_s3(params[:image][:file].tempfile, @image.id, resized_path)
      @result = GoogleApi.new.request(params[:image][:file].tempfile)
    else
      render :action => 'new'
    end
  end

  def list
    @images = Image.order("created_at DESC").page params[:page]
  end

  def about
  end

  def trans
    EasyTranslate.api_key = ENV['TRANS_SERVER_KEY']
    @translated = EasyTranslate.translate(params.delete_if{|p| p !~ /^word/ }.sort.collect!{ |k, v| v }.join(" "), :to => :ja)
  end

  def save_light_img_s3(img, id, path)
    Tinify.key = ENV["TINTPNG_API_KEY"]
    source = Tinify.from_file(img)
    resized = source.resize(
      method: "fit",
      width: 300,
      height: 300
    )
    resized.store(
      service: "s3",
      aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
      aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
      region: "ap-northeast-1",
      path: "api-img/#{path}"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/new.html.erb
<div class="image-step-wrapper">
  <p class="image-step-current">①画像UP</p><span class="triangle"></span>
  <p class="image-step">②文字列</p><span class="triangle"></span>
  <p class="image-step">③翻訳</p>
</div>

<%= form_for @image, url: upload_images_path, html: { multipart: true } do |f| %>
  <% if @image.errors.any?%>
    <p id="js-attention"><%= @image.errors[:file][0] %></p>
  <% end %>
  <p class="select-image-input"><%= f.file_field :file %></p>
  <p class="select-image-submit"><%= f.button 'アップロード'%></p>
<% end %>

app/views/images/upload.html.erb
<section class="image-upload-show-result">
  <div class="image-step-wrapper">
    <p class="image-step">①画像UP</p><span class="triangle"></span>
    <p class="image-step-current">②文字列</p><span class="triangle"></span>
    <p class="image-step">③翻訳</p>
  </div>
  <p class="image-uploaded"><%= image_tag "https://img.learntecs.xyz/#{@image.path}", :alt => @image.file.filename %></p>
  <p class="image-uploaded"><%= link_to "元の大きさで見る", @image.file.url, {target: "_blank"} %>
  <%= form_tag( trans_images_path, method: "post") do %>
  　<div class="image-upload-show-words">
      <% unless @result.nil? %>
        <% @result.each_with_index do |word, i|  %>
          <div class="image-upload-words-wrapper">
            <a class="js-image-upload-block-delete" href="javascript:void(0);">×</a>
            <span class="image-upload-words"><%= word %></span>
            <%= text_field_tag :"word#{i}" , word, style: "display:none;", class: "js-image-upload-edit-word" %>
          </div>
        <% end %>
      <% else %>
        <p class="image-no-result">画像から文字が読み取れませんでした。</p>
      <% end %>
    </div><!-- /mage-upload-show-words -->
    <p class="image-upload-submit"><%= button_tag '翻訳する' %></p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>GCV</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      <nav class="header-global-menu">
        <h1 class="header-main-title"><%=link_to "GCV", root_path %></h1>
        <p class="header-menu"><%= link_to "recently", list_images_path %></p>
        <p class="header-menu"><%= link_to "about", about_images_path %></p>
      </nav>
    </header>
    <div id="content-container">
      <%= yield %>
    </div>
    <footer>
      <nav class="footer-global-menu">
        <p class="footer-menu"><%= link_to "about", about_images_path %></p>
        <p class="footer-menu"><%= link_to "recently", list_images_path %></p>
        <p class="footer-menu"><%=link_to "home", root_path %></p>
      </nav>
      <small>&#169;dai-takahashi</small>
    </footer>
  </div><!-- /wrapper -->
</body>
</html>